#!/bin/bash
#
# 描述:该脚本用于启动UserServer服务

SERVERNAME="userserver"
DIR=/home/administrator/Project/WarGameServer/build/src/UserServer/bin
PROG=./UserServer
IP=0.0.0.0
PORT=9999

#start function
start()
{
	echo "Starting $SERVERNAME ..." 
	cd $DIR
	$PROG $IP $PORT &
	exit 0;
}

#stop funciton
stop()
{
	echo "Stoping $SERVERNAME ..."
	killall $DIR/$PROG
}

case "$1" in
start)
    start $2 $3
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac
exit
