#!/bin/bash
#
# 描述:该脚本用于启动RoomServer服务

SERVERNAME="roomserver"
DIR=/opt/RoomServer
PROG=./RoomServer
IP=0.0.0.0
PORT=6500

#start function
start()
{
	echo "Starting $SERVERNAME ..." 
	cd $DIR
	$PROG $IP $PORT &
	exit 0;
}

#stop funciton
stop()
{
	echo "Stoping $SERVERNAME ..."
	killall $DIR/$PROG
}

case "$1" in
start)
    start 
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac
exit
